- name: ACI - Create Tenant
  hosts: all
  tasks:
  - name: Create Tenant
    aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
        tenant: "{{ aci_tenant }}"
        description: "{{ aci_tenant_description }}"
        validate_certs: false
        state: present
