- name: ACI - Query all tenants
  hosts: all
  tasks:
  - name: Query all tenants
    aci_tenant:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      state: query
