- name: ACI - Query a tenant
  hosts: all
  gather_facts: false
  tasks:
  - name: Query a tenant
    aci_tenant:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      register: output
      validate_certs: false
      state: query
    register: output

  - debug:
          var: "{{ output }}"
