- name: ACI - Remove Tenant
  hosts: all
  tasks:
  - name: Remove Tenant
    aci_tenant:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      validate_certs: false
      state: absent
