- name: ACI - New Contract
  hosts: all
  tasks:
  - name: Add a new contract subject
    aci_contract_subject:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      contract: "{{ aci_contract_name }}"
      subject: "{{ aci_contract_subject }}"
      description: "{{ aci_contract_subject_description }}"
      reverse_filter: "{{ aci_contract_reverse | default('yes') }}"
      priority: "unspecified"
      dscp: "unspecified"
      validate_certs: false
      state: present
