- name: ACI - New Contract
  hosts: all
  tasks:
  - name: Remove a contract subject
    aci_contract_subject:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      contract: "{{ aci_contract_name }}"
      subject: "{{ aci_contract_subject }}"
      validate_certs: false
      state: absent
