- name: ACI - New Application Profile
  hosts: all
  tasks:
  - name: Modify a Bridge Domain
    aci_bd:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      bd: "{{ aci_tenant_bd }}"
      arp_flooding: {{ aci_bd_arp_flooding | default('yes') }}
      l2_unknown_unicast: {{ aci_bd_l2_unknown | default('flood') }}
      validate_certs: false
      state: present
