- name: ACI - New Application Profile
  hosts: all
  tasks:
  - name: Add Bridge Domain
    aci_bd:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      vrf: "{{ aci_tenant_vrf }}"
      bd: "{{ aci_tenant_bd }}"
      validate_certs: false
      state: present
