- name: ACI - New Application Profile
  hosts: all
  tasks:
  - name: Add an FC Bridge Domain
    aci_bd:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      vrf: "{{ item.aci_tenant_vrf }}"
      bd: "{{ item.aci_tenant_bd }}"
      validate_certs: false
      bd_type: fc
      enable_routing: "{{ item.aci_tenant_bd_routing | default('no') }}"
      state: present
    with_items:
      - "{{ bd }}"
