- name: ACI - New Application Profile
  hosts: all
  tasks:
  - name: Add an FC Bridge Domain
    aci_bd:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      validate_certs: false
      bd: storage
      bd_type: fc
      vrf: fc_vrf
      enable_routing: no
      state: present
