- name: ACI - New Application Profile
  hosts: all
  tasks:
  - name: Delete a Bridge Domain
    aci_bd:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      bd: web_servers
      validate_certs: false
      state: absent
