- name: Install Proxy
  hosts: all
  tasks:
    - name: Rebooting if needed
      command: sleep 2 && shutdown -r now "Ansible system package upgraded" removes=/var/run/reboot-required && sleep 1 
      become: true
      async: 1
      poll: 0
      ignore_errors: true
      register: restarted
      
    - name: waiting 30 secs for server to come back
      local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=30 timeout=60
      become: false