- name: ACI - New Subnet
  hosts: all
  tasks:
  - name: Add a new EPG
    aci_epg:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      bd: "{{ item.aci_tenant_bd }}"
      ap: "{{ item.aci_app_profile }}"
      epg: "{{ item.aci_epg_name }}"
      description: "{{ item.aci_epg_description }}"
      validate_certs: false
      preferred_group: yes
    with_items:
      - "{{ epg }}"
