- name: ACI - New Subnet
  hosts: all
  tasks:
  - name: Remove an EPG
    aci_epg:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      app_profile: "{{ aci_app_profile }}"
      epg: "{{ aci_epg_name }}"
      validate_certs: false
      state: absent
