- name: ACI - New Tenant 2
  hosts: all
  tasks:
  - name: Add a new tenant
    aci_tenant:
        host: "{{ inventory_hostname }}"
        username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
        password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
        tenant: "{{ aci_tenant }}"
        description: "{{ aci_tenant_description }}"
        state: present
