- name: ACI - New Tenant 2
  hosts: all
  tasks:
  - name: Display all variables/facts known for a host
    debug:
        var: hostvars[inventory_hostname]
        verbosity: 4

  - name: Add a new tenant
    aci_tenant:
        tenant: "{{ aci_tenant }}"
        description: "{{ aci_tenant_description }}"
        state: present
