- name: ACI - New Subnet
  hosts: all
  tasks:
  - name: New Subnet
    aci_bd_subnet:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ item.aci_tenant }}"
      bd: "{{ item.aci_tenant_bd }}"
      subnet_name: "{{ item.aci_subnet_name }}"
      description: "{{ item.aci_subnet_description }}"
      gateway: "{{ item.aci_subnet_dg }}"
      mask: "{{ item.aci_subnet_mask }}"
      scope: "{{ item.aci_subnet_scope | default('private') }}"
      route_profile_l3_out: "{{ item.aci_subnet_l3_out | default('') }}"
      route_profile: "{{ item.aci_subnet_profile | default('') }}"
      validate_certs: false
      state: present
    with_items:
      - "{{ subnets }}"
