- name: ==== Include Archlinux.yml ====
  include_tasks: Archlinux.yml
  when: ansible_os_family == 'Archlinux'
  static: no
- name: ==== Include Debian.yml ====
  include_tasks: Debian.yml
  when: ansible_os_family == 'Debian'
  static: no
- name: ==== Include RedHat.yml ====
  include_tasks: RedHat.yml
  when: ansible_os_family == 'RedHat'
  static: no
