- name: Create New User
  hosts: all
  tasks:
  - name: create user
    user: 
        name={{username}}
        createhome=yes
        state=present 
        password={{password}}
        append=yes
        groups=users
        shell="/bin/bash"
        update_password=always
        comment="User created via automation"
    register: newusercreated

  - name: User created
    debug: msg="Password for {{username}} is {{password}}"
    when: newusercreated.changed

  - name: configure sudoers
    lineinfile:   dest=/etc/sudoers.d/"{{username}}"
                  line="%wheel ALL=(ALL) ALL"
                  state=present
                  create=yes
                  validate='visudo -cf %s'
