- name: ACI - Remove Tenant VRF
  hosts: all
  tasks:
  - name: Query a VRF of a tenant
    aci_vrf:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      vrf: "{{ aci_tenant_vrf }}"
      state: query
