- name: Disable firewall
  service: name=firewalld state=stopped enabled=no
  ignore_errors: yes

- name: Disabled SELinux
  selinux:
    state: disabled
  ignore_errors: yes
  
- name: no iptables
  service:
    name: iptables
    state: stopped
  ignore_errors: yes