- name: ACI - New Application Profile
  hosts: all
  tasks:
  - name: New Application Profile
    aci_ap:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      ap: "{{ item.aci_app_profile }}"
      description: "{{ item.aci_app_profile_description }}"
      validate_certs: false
      state: present
    with_items:
      - "{{ anp }}"
