- name: ACI - Remove Application Profile
  hosts: all
  tasks:
  - name: Remove Application Profile
    aci_ap:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      ap: "{{ aci_app_profile }}"
      state: absent
