- name: ACI - New Contract
  hosts: all
  tasks:
  - name: New contract
    aci_contract:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      contract: "{{ aci_contract_name }}"
      description: "{{ aci_contract_description }}"
      scope: "{{ aci_contract_profile | default('vrf') }}"
      validate_certs: false
      state: present
