- name: ACI - Remove Contract
  hosts: all
  tasks:
  - name: Remove Contract
    aci_contract:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env','ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env','ANSIBLE_NET_PASSWORD') }}"
      tenant: "{{ aci_tenant }}"
      contract: "{{ aci_contract_name }}"
      validate_certs: false
      state: absent
