- name: Cisco Spark - Text Message to a Room
  hosts: all
  tasks:
  - name: Text Message to a Room
    cisco_spark:
      recipient_type: roomId
      recipient_id: "{{ roomid }}"
      message_type: markdown
      personal_token: "{{ token }}"
      message: "{{ message }}"
