- name: Update Base OS
  hosts: all
  tasks:
    - name: Cisco Spark - Text Message to a Room
      cisco_spark:
        recipient_type: roomId
        recipient_id: "{{ room_id }}"
        message_type: text
        personal_token: "{{ token }}"
        message: "{{ message }}"
